server: 
 port: 23333
 session-timeout: 30
 tomcat.max-threads: 0
 tomcat.uri-encoding: UTF-8


spring:
  user:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306:3306/rise?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456 # 浣犵殑鏁版嵁搴撳瘑鐮?
  web:
    cors:
      exposed-headers:
        "Content-Type": true
        "Authorization": true
        "X-Requested-With": true
        "x-http-method-override": true

servlet:
    # 涓婁紶闄愬畾鍙傛暟
    multipart:
      # 鏄惁鍚敤鍒嗘涓婁紶鏀寔
      enabled: true
      # 鏈€澶ц姹傚ぇ灏?
      max-request-size: 10MB
      # 鏈€澶ф枃浠剁殑澶у皬
      max-file-size: 5MB
      #涓婁紶鏂囦欢鐨勪腑闂翠綅缃?
      location: C:/涓存椂鏂囦欢

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

riseout:
  url: http://localhost:9999
  fileurl: C:/video/   #鏂囦欢鐨勫疄闄呬綅缃?
  fileuploadpath: C:\video\ #涓婁紶鏂囦欢鐨勫疄闄呬綅缃?





